name: Comment on PR

on:
  workflow_run:
    workflows: [Upload data]
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      GITHUB_RUN_ID: ${{ github.event.workflow_run.workflow.id }}
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v3
        with:
          name: pr_number
      - name: 'Comment on PR'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');

            const issue_number = Number(fs.readFileSync('./pr_number'));

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number,
              body: 'Thank you for the PR!'
            });
